-- Run this in Supabase SQL Editor.
create table if not exists public.group_photos (
  id bigint generated by default as identity primary key,
  member_name text not null,
  member_role text not null,
  file_path text not null,
  public_url text not null,
  created_at timestamptz not null default now()
);

alter table public.group_photos enable row level security;

create policy "Anyone can view group photos"
on public.group_photos for select
to anon
using (true);

create policy "Anyone can upload group photo records"
on public.group_photos for insert
to anon
with check (true);

insert into storage.buckets (id, name, public)
values ('group-photos', 'group-photos', true)
on conflict (id) do update set public = true;

create policy "Anyone can upload group photos"
on storage.objects for insert
to anon
with check (bucket_id = 'group-photos');

create policy "Anyone can view group photos"
on storage.objects for select
to anon
using (bucket_id = 'group-photos');
